/**
 * Every action the audit log records. Kept isomorphic so the audit browser can
 * offer the list as a filter without importing the server writer.
 */
export const AUDIT_ACTIONS = [
  // platform
  "SCHOOL_REGISTERED",
  "SCHOOL_EMAIL_CODE_SENT",
  "SCHOOL_EMAIL_VERIFIED",
  "SCHOOL_EMAIL_VERIFY_FAILED",
  "SCHOOL_UNDER_REVIEW",
  "SCHOOL_APPROVED",
  "SCHOOL_REJECTED",
  "SCHOOL_SUSPENDED",
  "SCHOOL_REACTIVATED",
  "SCHOOL_ADMIN_CREATED",
  "SUBSCRIPTION_UPDATED",
  "PLAN_UPDATED",
  "OFFER_CREATED",
  "OFFER_UPDATED",
  "OFFER_DELETED",
  // identity
  "USER_LOGIN",
  "USER_LOGIN_FAILED",
  "USER_LOGOUT",
  "PASSWORD_CHANGED",
  "PASSWORD_RESET",
  "USER_DEACTIVATED",
  "USER_REACTIVATED",
  "PORTAL_ACCESS_GRANTED",
  "API_TOKEN_CREATED",
  "API_TOKEN_REVOKED",
  // academics
  "ACADEMIC_SESSION_CREATED",
  "ACADEMIC_SESSION_ACTIVATED",
  "CLASS_UPDATED",
  "STREAM_UPDATED",
  "SUBJECT_UPDATED",
  "SECTION_CREATED",
  "SECTION_UPDATED",
  // people
  "STUDENT_CREATED",
  "STUDENT_UPDATED",
  "STUDENT_ENROLLED",
  "PARENT_LINKED",
  "TEACHER_CREATED",
  "TEACHER_UPDATED",
  "TEACHER_ASSIGNED",
  "TEACHER_UNASSIGNED",
  // operations
  "TIMETABLE_UPDATED",
  "ATTENDANCE_MARKED",
  "STAFF_ATTENDANCE_MARKED",
  "ADMISSION_SUBMITTED",
  "ADMISSION_STATUS_CHANGED",
  "ADMISSION_ACCEPTED",
  "ADMISSION_REJECTED",
  "NOTICE_PUBLISHED",
  "NOTICE_UPDATED",
  "EVENT_UPDATED",
  "WEBSITE_UPDATED",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
