/**
 * One outline icon set for the whole app; icons support the words, never
 * replace them. A plain module (not "use client") so Server Components can use
 * the map too.
 */
import {
  BarChart3Icon,
  BookOpenIcon,
  Building2Icon,
  BusIcon,
  CalendarClockIcon,
  CalendarDaysIcon,
  CalendarOffIcon,
  CircleUserIcon,
  ClipboardCheckIcon,
  ClipboardListIcon,
  ClockIcon,
  FolderOpenIcon,
  GlobeIcon,
  GraduationCapIcon,
  HandshakeIcon,
  HeartHandshakeIcon,
  IdCardIcon,
  InboxIcon,
  KeyRoundIcon,
  LayoutDashboardIcon,
  LibraryIcon,
  LifeBuoyIcon,
  type LucideIcon,
  MegaphoneIcon,
  MessageSquareWarningIcon,
  NotebookPenIcon,
  PackageIcon,
  ReceiptTextIcon,
  ScrollTextIcon,
  SettingsIcon,
  TagIcon,
  UserCogIcon,
  UserPlusIcon,
  UsersIcon,
  WalletCardsIcon,
  WalletIcon,
} from "lucide-react";

import type { NavIcon } from "@/lib/nav";

export const NAV_ICONS: Record<NavIcon, LucideIcon> = {
  dashboard: LayoutDashboardIcon,
  schools: Building2Icon,
  offers: TagIcon,
  inbox: InboxIcon,
  audit: ScrollTextIcon,
  plans: WalletCardsIcon,
  students: UsersIcon,
  teachers: UserCogIcon,
  academics: BookOpenIcon,
  timetable: ClockIcon,
  attendance: ClipboardCheckIcon,
  reports: BarChart3Icon,
  notices: MegaphoneIcon,
  events: CalendarDaysIcon,
  holidays: CalendarOffIcon,
  exams: GraduationCapIcon,
  leave: CalendarClockIcon,
  meetings: HandshakeIcon,
  complaints: MessageSquareWarningIcon,
  staff: IdCardIcon,
  transport: BusIcon,
  library: LibraryIcon,
  inventory: PackageIcon,
  homework: NotebookPenIcon,
  records: ClipboardListIcon,
  materials: FolderOpenIcon,
  admissions: UserPlusIcon,
  website: GlobeIcon,
  account: CircleUserIcon,
  tokens: KeyRoundIcon,
  children: HeartHandshakeIcon,
  fees: WalletIcon,
  expenses: ReceiptTextIcon,
  settings: SettingsIcon,
  support: LifeBuoyIcon,
};

